# Generated by Django 3.1 on 2020-08-20 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='site_name',
            field=models.CharField(max_length=200),
        ),
    ]
